discussion/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("todolist/", include("todolist.urls")),
    path("todolist/", include("eventlist.urls"))
]

discussion/eventlist/urls.py
from django.urls import path
# import the views.py from the same folder
from . import views


app_name = 'eventlist'

urlpatterns = [
	path('event/<int:eventitem_id>/', views.eventitem, name = "vieweventitem"),
	path('index', views.index, name = "index"),
	path('add_event', views.add_event, name = "add_event"),
]

discussion/todolist/urls.py
from django.urls import path
# import the views.py from the same folder
from . import views


app_name = 'todolist'

urlpatterns = [
	path('index', views.index, name = 'index'),
	path('<int:todoitem_id>/', views.todoitem, name = "viewtodoitem"),
	path('register', views.register, name = "register"),
	path('change_password', views.change_password, name = "change_password"),
	path('login', views.login_user, name = "login"),
	path('logout', views.logout_user, name = "logout"),
	path('add_task', views.add_task, name = "add_task"),
	path('<int:todoitem_id>/update_task', views.update_task, name = "update_task"),
	path('<int:todoitem_id>/delete', views.delete_task, name = "delete_task")
]

discussion/todolist/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User

class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=500)
	status = models.CharField(max_length=50, default = "pending")
	date_created = models.DateTimeField("date created")
	user = models.ForeignKey(User, on_delete = models.RESTRICT, default = "")

discussion/todolist/forms.py
from django import forms

class RegisterForm(forms.Form):
	username = forms.CharField(label = "username", max_length = 20)
	password = forms.CharField(label = "password", max_length = 20)
	confirm = forms.CharField(label = "confirm", max_length = 20)
	firstname = forms.CharField(label = "firstname", max_length = 20)
	lastname = forms.CharField(label = "lastname", max_length = 20)
	email = forms.CharField(label = "email")

class LoginForm(forms.Form):
	username = forms.CharField(label = "username", max_length = 20)
	password = forms.CharField(label = "password", max_length = 20)

class AddTaskForm(forms.Form):
	task_name = forms.CharField(label = 'task_name', max_length =50)
	description = forms.CharField(label = 'description', max_length = 200)

class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label = 'task_name', max_length =50)
	description = forms.CharField(label = 'description', max_length = 200)
	status = forms.CharField(label = 'status', max_length = 50)

class ChangePasswordForm(forms.Form):
	changepassword = forms.CharField(label = "changepassword", max_length = 20)
	changeconfirm = forms.CharField(label = "changeconfirm", max_length = 20)

discussion/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.

# The from keyword allows importing of necessary classes/modules, methods and others files needed in our application from the django.http package while the import keyword defines what we are importing from the package
from django.http import HttpResponse

# Local imports
from .models import ToDoItem

# import the built in User Model
from django.contrib.auth.models import User

# to use the template created:
# from django.template import loader

# import the authenticate function
from django.contrib.auth import authenticate, login, logout

from django.forms.models import model_to_dict

from django.contrib.auth.hashers import make_password

from .forms import LoginForm, AddTaskForm, UpdateTaskForm, RegisterForm, ChangePasswordForm

from django.utils import timezone

def index(request):
	todoitem_list = ToDoItem.objects.filter(user_id = request.user.id)
	context = {
		'todoitem_list': todoitem_list,
		"user": request.user
	}

	return render(request, "index.html", context)

def todoitem(request, todoitem_id):
	# response = f"You are viewing the details of {todoitem_id}"
	# return HttpResponse(response)

	todoitem = get_object_or_404(ToDoItem, pk = todoitem_id)

	return render(request, "todoitem.html", model_to_dict(todoitem))


# this function is responsible for registering on our application
def register(request):
	context = {}

	users = User.objects.all()
	is_user_registered = False

	# if this is a post request we need to process the form data
	if request.method == "POST":

		form = RegisterForm(request.POST)

		if form.is_valid() == False:
			form = RegisterForm()
			
		else:
			password = form.cleaned_data['password']
			confirm = form.cleaned_data['confirm']
			if password == confirm:
				username = form.cleaned_data['username']
				firstname = form.cleaned_data['firstname']
				lastname = form.cleaned_data['lastname']
				email = form.cleaned_data['email']
				is_staff = False
				is_active = True
				hashed_password = make_password(password)
				user = User.objects.create(username=username, email=email, password=hashed_password, first_name=firstname, last_name=lastname)

				for existing_user in users:
					if existing_user.username == username:
						is_user_registered = True
						break

				if is_user_registered == False:
					# to save our user
					user.save()

				if user is not None:
					context = {
						'is_user_registered': is_user_registered,
						'username' : username,
						'password' : password
					}
					login(request, user)
					return redirect("todolist:index")
			else:
				context = {
					'error' : True
				}
	
	
	return render(request, "register.html", context)


def change_password(request):
	
	is_user_authenticated = False
	context = {}

	if request.method == "POST":

		form = ChangePasswordForm(request.POST)

		if form.is_valid() == False:
			form = ChangePasswordForm()
		else:

			username = request.user.username
			password = form.cleaned_data['changepassword']
			confirm = form.cleaned_data['changeconfirm']
			user = authenticate(username = username, password = password)

			if user is not None and password == confirm:
				authenticated_user = User.objects.get(username = username)
				authenticated_user.set_password(password)
				authenticated_user.save()

				is_user_authenticated = True
			else:
				context = {
					'error' : True
				}
			
	
			context = {
				"is_user_authenticated": is_user_authenticated
			}

	return render(request, "change_password.html", context)
			

def login_user(request):
	context = {}

	# if this is a post request we need to process the form data
	if request.method == "POST":

		form = LoginForm(request.POST)

		if form.is_valid() == False:
			form = LoginForm()
			
		else:
			print(form)
			# cleaned_data retrieves the information from the form
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			user = authenticate(username = username, password = password)

			if user is not None:
				context = {
					'username' : username,
					'password' : password
				}
				login(request, user)
				return redirect("todolist:index")
			else:
				context = {
					'error' : True
				}
			
	
	return render(request, "login.html", context)








	# username = 'johndoe'
	# password = 'johndoe1234567'

	# user = authenticate(username = username, password = password)

	

def logout_user(request):
	logout(request)
	return redirect("todolist:index")


def add_task(request):
	context = {}

	if request.method == 'POST':
		form = AddTaskForm(request.POST)

		if form.is_valid() == False:
			form = AddTaskForm()

		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']

			duplicates = ToDoItem.objects.filter(task_name = task_name, user_id = request.user.id)

			if not duplicates:
				# create an ovbject based on the ToDoItem model and saves to the record in the database

				ToDoItem.objects.create(task_name = task_name, description = description, date_created = timezone.now(), user_id = request.user.id)

				return redirect("todolist:index")
			else:
				context = {
					'error' : True
				}

	return render(request, "add_task.html", context)



def update_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk = todoitem_id)

	context = {
		"user" : request.user,
		"todoitem_id": todoitem_id,
		"task_name": todoitem[0].task_name,
		"description": todoitem[0].description,
		"status": todoitem[0].status
	}

	if request.method == "POST":
		form = UpdateTaskForm(request.POST)

		if form.is_valid() == False:
			form = UpdateTaskForm()
		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if todoitem:
				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status

				todoitem[0].save()

				return redirect("todolist:viewtodoitem", todoitem_id = todoitem[0].id)

			else:
				context = {
					"error" : True
				}

	return render(request, "update_task.html", context)

def delete_task(request, todoitem_id):
	ToDoItem.objects.filter(pk = todoitem_id).delete()

	return redirect("todolist:index")

discussion/todolist/templates/add_task.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}
	<h1 class = "text-center my-3">Adding a Task</h1>
	<div class = "container">
		<div class = "row">
			<div class = "col-6 offset-3">
				{% if error == True %}
					<p class = "text-danger">Duplicate Task Found!</p>
				{% endif %}
				<form action="{% url 'todolist:add_task' %}" method="POST">
					
					{% csrf_token %}

					<div class="mb-3">
					    <label for="task_name">Task Name: </label>
					    <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
					    <label for="description">Description: </label>
					    <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
					</div>

					<div class="text-center">
				    	<input class="btn btn-success" type="submit" value="Add Task">
					</div>

				</form>
			</div>
		</div>
	</div>


{% endblock %}

discussion/todolist/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}To Do App{% endblock%}</title>
	<!-- Bootstrap Link -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
</head>
<body>
	<!-- <h1>Hello Batch 278!</h1> -->
	<!-- The "include" keword unlike the "extends" keyword  allows to inject specific templates in certain sections of a page-->
	{% include "navbar.html" %}

	{% block content %}
		<!-- block denotes a placeholder -->

	{% endblock %}

	{% block event %}
		<!-- block denotes a placeholder -->

	{% endblock %}

	<!-- Bootstrap Script -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
</body>
</html>

discussion/todolist/templates/change_password.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
	<h1 class = "text-center my-3">Update Profile Form</h1>
	<div class = "container">
		<div class = "row">
			<div class = "col-6 offset-3">

				{% if error == True %}
					<p class = "text-danger">Invalid details. Please input correct details.</p>
				{% endif %}
				
				<form action = "{% url 'todolist:change_password' %}" method = "POST">
					<!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
					<!-- CSRF occurs when a malicious website contains link, a from button or some javascript that is intended to perform some action in our website -->
					{% csrf_token %}
				  <div class="mb-3">
				    <label for="changepassword" class="form-label">Password:</label>
				    <input 
				    	type="password" 
				    	class="form-control" 
				    	id="changepassword"
				    	name = "changepassword"
				    	value = "{{ changepassword }}"
				    	maxlength="20" 
				    	required
				    	>

				  </div>
				  <div class="mb-3">
				    <label for="changeconfirm" class="form-label">Confirm Password:</label>
				    <input 
				    	type="password" 
				    	class="form-control" 
				    	id="changeconfirm"
				    	name = "changeconfirm"
				    	value = "{{ changeconfirm }}"
				    	maxlength="20" 
				    	required
				    	>

				  </div>
				  
				  <button type="submit" class="btn btn-primary">Change Password</button>
				</form>
				
			</div>
			
		</div>
	</div>

{% endblock %}

discussion/todolist/templates/index.html
{% extends 'base.html' %}

{%block title%}Home{% endblock %}

{% block content %}
	{% if todoitem_list and user.is_anonymous == False %}
		<h1 class = "text-center my-3">Welcome {{user.first_name}} {{user.last_name}}!</h1>

		<div class = "container">
			<div class = 'row'>
				<h3 class = "text-center mb-3">My Tasks</h3>
				<ul class = " list-group text-center col-lg-4 offset-lg-4">
				{% for todoitem in todoitem_list %}
					<li class = "list-group-item"><a class = "text-decoration-none"href = "{% url 'todolist:viewtodoitem' todoitem.id %}">{{todoitem.task_name}}</a></li>
				{% endfor%}	
				</ul>
			</div>
		</div>

		
	{% elif todoitem_list.count == 0 and user.is_anonymous == False %}
		<h1 class = "text-center my-3">Welcome {{user.first_name}} {{user.last_name}}!</h1>
		<p class = "text-center my-3">No tasks have been created.</p>
	{%else%}
		<h1 class = "text-center my-3">You are not authorized to access this page.</h1>
		<p class = "text-center my-3">Kindly login <a href = "{% url 'todolist:login' %}">here</a>.</p>
	{% endif %}


{% endblock %}

{% block event %}
	<!-- block denotes a placeholder -->

{% endblock %}

discussion/todolist/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
	<h1 class = "text-center my-3">Login Form</h1>
	<div class = "container">
		<div class = "row">
			<div class = "col-6 offset-3">

				{% if error == True %}
					<p class = "text-danger">Invalid credentials, please check your username and password or register first</p>
				{% endif %}
				
				<form action = "{% url 'todolist:login' %}" method = "POST">
					<!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
					<!-- CSRF occurs when a malicious website contains link, a from button or some javascript that is intended to perform some action in our website -->
					{% csrf_token %}
				  <div class="mb-3">
				    <label for="username" class="form-label">Username:</label>
				    <input 
				    	type="text" 
				    	class="form-control" 
				    	id="username" 
				    	value = "{{ username }}"
				    	name = "username"
				    	maxlength = "20"
				    	required 
				    	>
				  </div>
				  <div class="mb-3">
				    <label for="password" class="form-label">Password:</label>
				    <input 
				    	type="password" 
				    	class="form-control" 
				    	id="password"
				    	name = "password"
				    	value = "{{ password }}"
				    	maxlength="20" 
				    	required
				    	>

				  </div>
				  
				  <button type="submit" class="btn btn-primary">Login</button>
				</form>
				
			</div>
			
		</div>
	</div>

{% endblock %}

discussion/todolist/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="">To Do App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:add_task' %}">Add Task</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'eventlist:add_event' %}">Add Event</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:change_password' %}">Update Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href = "{% url 'todolist:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href = "{% url 'todolist:logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

discussion/todolist/templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
	<h1 class = "text-center my-3">Registration Form</h1>
	<div class = "container">
		<div class = "row">
			<div class = "col-6 offset-3">

				{% if error == True %}
					<p class = "text-danger">Invalid details. Please input correct details.</p>
				{% endif %}
				
				<form action = "{% url 'todolist:register' %}" method = "POST">
					<!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
					<!-- CSRF occurs when a malicious website contains link, a from button or some javascript that is intended to perform some action in our website -->
					{% csrf_token %}
				  <div class="mb-3">
				    <label for="username" class="form-label">Username:</label>
				    <input 
				    	type="text" 
				    	class="form-control" 
				    	id="username" 
				    	value = "{{ username }}"
				    	name = "username"
				    	maxlength = "20"
				    	required 
				    	>
				  </div>
				  <div class="mb-3">
				    <label for="firstname" class="form-label">First Name:</label>
				    <input 
				    	type="text" 
				    	class="form-control" 
				    	id="firstname" 
				    	value = "{{ firstname }}"
				    	name = "firstname"
				    	maxlength = "20"
				    	required 
				    	>
				  </div>
				  <div class="mb-3">
				    <label for="lastname" class="form-label">Last Name:</label>
				    <input 
				    	type="text" 
				    	class="form-control" 
				    	id="lastname" 
				    	value = "{{ lastname }}"
				    	name = "lastname"
				    	maxlength = "20"
				    	required 
				    	>
				  </div>
				  <div class="mb-3">
				    <label for="email" class="form-label">Email:</label>
				    <input 
				    	type="email" 
				    	class="form-control" 
				    	id="email" 
				    	value = "{{ email }}"
				    	name = "email"
				    	required 
				    	>
				  </div>
				  <div class="mb-3">
				    <label for="password" class="form-label">Password:</label>
				    <input 
				    	type="password" 
				    	class="form-control" 
				    	id="password"
				    	name = "password"
				    	value = "{{ password }}"
				    	maxlength="20" 
				    	required
				    	>

				  </div>
				  <div class="mb-3">
				    <label for="confirm" class="form-label">Confirm Password:</label>
				    <input 
				    	type="password" 
				    	class="form-control" 
				    	id="confirm"
				    	name = "confirm"
				    	value = "{{ confirm }}"
				    	maxlength="20" 
				    	required
				    	>

				  </div>
				  
				  <button type="submit" class="btn btn-primary">Register</button>
				</form>
				
			</div>
			
		</div>
	</div>

{% endblock %}

discussion/todolist/templates/todoitem.html
{% extends 'base.html' %}

{% block title %}Task{% endblock %}

{% block content %}
	<div class="text-center mt-3">
		<h1>{{task_name}}</h1>

		<h3>Description:</h3>
		<p>{{description}}</p>

		<h3>Status:</h3>
		<p>{{status}}</p>
		<button class="btn btn-success mx-1">
			<a class="text-decoration-none" href = "{% url 'todolist:update_task' id %}">Edit this task</a>
		</button>
		<button class="btn btn-danger mx-1">
			<a class="text-decoration-none" href = "{% url 'todolist:delete_task' id %}">Delete this task</a>
		</button>
		<button class="btn btn-warning mx-1">
			<a class="text-decoration-none" href = "{% url 'todolist:index' %}">Back to index page!</a>
		</button>
		
	</div>
{% endblock %}

discussion/todolist/templates/update_task.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
		<div class="container">
			<div class="row">
				<div class="col-6 offset-3">
					<h1 class="text-center mt-3">Update Task</h1>
					{% if error == True %}
						<p class="text-danger text-center">Task not found!</p>
					{% endif %}
					<form action="{% url 'todolist:update_task' todoitem_id %}" method="POST">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="task_name">Task Name: </label>
                        <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
                    </div>

                    <div class="mb-3">
                        <label for="description">Description: </label>
                        <textarea class="form-control" name="description" required>{{ description }}</textarea>
                    </div>

                    <div class="mb-3">
                        <label for="status">Status: </label>
                        <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
                    </div>

                    <div class="text-center">
                        <input class="btn btn-success" type="submit" value="Update Task">
                    </div>

                </form>
				</div>
			</div>
		</div>

	{% endif %}

{% endblock %}