discussion/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("todolist/", include("todolist.urls")),
    path("todolist/", include("eventlist.urls"))
]

discussion/eventlist/urls.py
from django.urls import path
# import the views.py from the same folder
from . import views


app_name = 'eventlist'

urlpatterns = [
	path('event/<int:eventitem_id>/', views.eventitem, name = "vieweventitem"),
	path('index', views.index, name = "index"),
	path('add_event', views.add_event, name = "add_event"),
]

discussion/todolist/urls.py
from django.urls import path
# import the views.py from the same folder
from . import views


app_name = 'todolist'

urlpatterns = [
	path('index', views.index, name = 'index'),
	path('<int:todoitem_id>/', views.todoitem, name = "viewtodoitem"),
	path('register', views.register, name = "register"),
	path('change_password', views.change_password, name = "change_password"),
	path('login', views.login_user, name = "login"),
	path('logout', views.logout_user, name = "logout"),
	path('add_task', views.add_task, name = "add_task"),
	path('<int:todoitem_id>/update_task', views.update_task, name = "update_task"),
	path('<int:todoitem_id>/delete', views.delete_task, name = "delete_task")
]

discussion/eventlist/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User

class EventItem(models.Model):
	event_name = models.CharField(max_length=50)
	description = models.CharField(max_length=500)
	status = models.CharField(max_length=50, default = "pending")
	date_created = models.DateTimeField("date created")
	user = models.ForeignKey(User, on_delete = models.RESTRICT, default = "")

discussion/eventlist/forms.py
from django import forms

class AddEventForm(forms.Form):
	event_name = forms.CharField(label = 'event_name', max_length =50)
	description = forms.CharField(label = 'description', max_length = 200)

discussion/eventlist/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.

from django.http import HttpResponse

from .models import EventItem

from django.contrib.auth.models import User

from django.forms.models import model_to_dict

from .forms import AddEventForm

from django.utils import timezone

def index(request):

	eventitem_list = EventItem.objects.filter(user_id = request.user.id)
	context = {
		'eventitem_list': eventitem_list,
		"user": request.user
	}

	return render(request, "index.html", context)


def eventitem(request, eventitem_id):

	eventitem = get_object_or_404(EventItem, pk = eventitem_id)

	return render(request, "eventitem.html", model_to_dict(eventitem))


def add_event(request):
	context = {}

	if request.method == 'POST':
		form = AddEventForm(request.POST)

		if form.is_valid() == False:
			form = AddEventForm()

		else:
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']

			duplicates = EventItem.objects.filter(event_name = event_name, user_id = request.user.id)

			if not duplicates:
				# create an ovbject based on the ToDoItem model and saves to the record in the database

				EventItem.objects.create(event_name = event_name, description = description, date_created = timezone.now(), user_id = request.user.id)

				return redirect("eventlist:index")
			else:
				context = {
					'error' : True
				}

	return render(request, "add_event.html", context)

discussion/eventlist/templates/add_event.html
{% extends 'base.html' %}

{% block title %}Add Event{% endblock %}

{% block content %}
	<h1 class = "text-center my-3">Adding an Event</h1>
	<div class = "container">
		<div class = "row">
			<div class = "col-6 offset-3">
				{% if error == True %}
					<p class = "text-danger">Duplicate Event Found!</p>
				{% endif %}
				<form action="{% url 'eventlist:add_event' %}" method="POST">
					
					{% csrf_token %}

					<div class="mb-3">
					    <label for="event_name">Event Name: </label>
					    <input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
					    <label for="description">Description: </label>
					    <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
					</div>

					<div class="text-center">
				    	<input class="btn btn-success" type="submit" value="Add Event">
					</div>

				</form>
			</div>
		</div>
	</div>


{% endblock %}

discussion/eventlist/templates/eventitem.html
{% extends 'base.html' %}

{% block title %}Event{% endblock %}

{% block content %}
	<div class="text-center mt-3">
		<h1>{{event_name}}</h1>

		<h3>Description:</h3>
		<p>{{description}}</p>

		<h3>Status:</h3>
		<p>{{status}}</p>
		<button class="btn btn-warning mx-1">
			<a class="text-decoration-none" href = "{% url 'todolist:index' %}">Back to index page!</a>
		</button>
		
	</div>
{% endblock %}

discussion/eventlist/templates/index.html
{% extends 'base.html' %}

{% block content %}
	{% if eventitem_list and user.is_anonymous == False %}
		<h1 class = "text-center my-3">Welcome {{user.first_name}} {{user.last_name}}!</h1>

		<div class = "container">
			<div class = 'row'>
				<h3 class = "text-center mb-3">My Events</h3>
				<ul class = " list-group text-center col-lg-4 offset-lg-4">
				{% for eventitem in eventitem_list %}
					<li class = "list-group-item"><a class = "text-decoration-none"href = "{% url 'eventlist:vieweventitem' eventitem.id %}">{{eventitem.event_name}}</a></li>
				{% endfor%}	
				</ul>
			</div>
		</div>

		
	{% elif eventitem_list.count == 0 and user.is_anonymous == False %}
		<p class = "text-center my-3">No events have been created.</p>
	{%else%}
		<p class = "text-center my-3">No events have been created.</p>

	{% endif %}

{% endblock %}